### ISSUE TITLE
Wiki Feedback

### ISSUE THREAD

**Issue by edherm** [EdSanchezHer/dont-forget-to-sweat#4]
Hello! 

I am reviewing all groups wikis today and wanted to drop a few things here that I would like y'all to take care of.

## General
- [x] Add a link to your user stories.
- [x] Add your schema (either using markdown tables or by embedding an image of your schema diagram. After adding your schema, add a link in the Home of your wiki to the schema page.

## MVP Feature List
- [x] The title of this wiki page is "Don't Forget The Sweat", but your repo is "Don't forget to Sweat". Which is the title you are going with? 

Once these are taken care of, please drop your responses/updates here as a response to this issue.

Thanks, y'all!!
Ed

**Comment by jasole1983** [comment]
I believe all issues have been corrected, but I think we just failed to alert you to them (oops).  Should be up to snuff now.  Thanks for the pointers.
